version: "3.9"
services:
  pentryansvar:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/SSISPentryAnsvarServer
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"